### ISSUE TITLE
Please re-launch ipfs2ar service

### ISSUE THREAD

**Issue by PetrichorA** [cedriking/ipfsarweave#10]
As mentioned in #9 the wallet of `ipfs2ar` has been empty for nearly a month now, and the spammers have finally gone away (as you can see in [Arweave Blockchain Explorer](https://scar.vercel.app/#/address/-5VMrJ6SIbT2yQT0cl_ftRJlDj4AzEq0e8ew8rYCNsE)). 

For those people who don't have the ability to deploy their own `arkb` server, `ipfs2ar` is a must to move their file from the IPFS network to the Arweave network. 

There are many use cases that are meaningful and don't violate your ToS, and I think it's high time that you got the `ipfs2ar` service re-launched.

**Comment by cedriking** [comment]
Hello @PetrichorA spammers haven't "gone away" nor stopped, we just don't have funds for the service anymore and that's why you see it doesn't send any transactions. 

You are always free to start your own service, or even a local server with your wallet to be able to use IPFS 2 Arweave locally or on your own server.
