### ISSUE TITLE
[Bug] Fail to pin IPFS hash

### ISSUE THREAD

**Issue by PetrichorA** [cedriking/ipfsarweave#9]
IPFS hash: `bafybeiclkksicudsdauhv5tgvifzbqh5hbul5fi6j27bsdugnymbombg5q`  
request: GET `https://ipfs2arweave.com/permapin/bafybeiclkksicudsdauhv5tgvifzbqh5hbul5fi6j27bsdugnymbombg5q`  
response: `{"arweaveId":"m5ATHTQDOrWjqyCp7SrdaxIliNo_NxpXY5mhih_QHyk","ipfsHash":"bafybeiclkksicudsdauhv5tgvifzbqh5hbul5fi6j27bsdugnymbombg5q","statusCode":208}`

However, `https://arweave.net/tx/m5ATHTQDOrWjqyCp7SrdaxIliNo_NxpXY5mhih_QHyk` returned 404 error. The transaction was not even created. 

Please fix it.

**Comment by PetrichorA** [comment]
@cedriking unable to pin again with the same error

**Comment by cedriking** [comment]
Hello there @PetrichorA , I would recommend you use arkb: https://github.com/textury/arkb to deploy your content to Arweave + IPFS. 

Ipfs2Ar is a free (to the users), but a limited service, due to all the abuse and spam we get. 
With arkb you don't have these limitations since you are the one funding your deploys.
